ALTER TABLE "Regiao" ADD COLUMN IF NOT EXISTS "uf" TEXT;
ALTER TABLE "Regiao" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Regiao" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
