ALTER TABLE "Pessoa" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Demanda" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "ObservacaoPessoa" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "VinculoRede" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
