ALTER TABLE "Pessoa" ADD COLUMN IF NOT EXISTS "cpf" TEXT;
ALTER TABLE "Pessoa" ADD COLUMN IF NOT EXISTS "telefoneFixo" TEXT;
ALTER TABLE "Pessoa" ADD COLUMN IF NOT EXISTS "orientacaoSexual" TEXT;
ALTER TABLE "Pessoa" ADD COLUMN IF NOT EXISTS "religiao" TEXT;
ALTER TABLE "Pessoa" ADD COLUMN IF NOT EXISTS "escolaridade" TEXT;
